// <auto-generated />
using System;
using DAL.Data.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(TheraFlowDbContext))]
    [Migration("20250417224647_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BLL.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<int>("SpecialistId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("SpecialistId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateTime(2025, 4, 10, 10, 30, 0, 0, DateTimeKind.Utc),
                            ClientId = 1,
                            SpecialistId = 1
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDate = new DateTime(2025, 4, 11, 14, 30, 0, 0, DateTimeKind.Utc),
                            ClientId = 2,
                            SpecialistId = 2
                        });
                });

            modelBuilder.Entity("BLL.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1990, 5, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ivan@example.com",
                            FullName = "Іван Іванов",
                            Phone = "1234567890"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1995, 8, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "maria@example.com",
                            FullName = "Марія Коваль",
                            Phone = "0987654321"
                        });
                });

            modelBuilder.Entity("BLL.Entities.ConsultationNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("ConsultationNotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentId = 1,
                            Notes = "Обговорили тривожність та техніки заземлення."
                        },
                        new
                        {
                            Id = 2,
                            AppointmentId = 2,
                            Notes = "Перший сеанс. Уточнено цілі терапії."
                        });
                });

            modelBuilder.Entity("BLL.Entities.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SpecialistId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SpecialistId");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = new DateTime(2025, 4, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            SpecialistId = 1,
                            StartTime = new DateTime(2025, 4, 10, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            EndTime = new DateTime(2025, 4, 11, 16, 0, 0, 0, DateTimeKind.Utc),
                            SpecialistId = 2,
                            StartTime = new DateTime(2025, 4, 11, 14, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BLL.Entities.Specialist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Specialists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "olena@theraflow.com",
                            FullName = "Олена Психолог",
                            Specialty = "Когнітивно-поведінкова терапія"
                        },
                        new
                        {
                            Id = 2,
                            Email = "andrii@theraflow.com",
                            FullName = "Андрій Терапевт",
                            Specialty = "Гештальт-терапія"
                        });
                });

            modelBuilder.Entity("BLL.Entities.Appointment", b =>
                {
                    b.HasOne("BLL.Entities.Client", "Client")
                        .WithMany("Appointments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BLL.Entities.Specialist", "Specialist")
                        .WithMany("Appointments")
                        .HasForeignKey("SpecialistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Specialist");
                });

            modelBuilder.Entity("BLL.Entities.ConsultationNote", b =>
                {
                    b.HasOne("BLL.Entities.Appointment", "Appointment")
                        .WithOne("Note")
                        .HasForeignKey("BLL.Entities.ConsultationNote", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("BLL.Entities.Schedule", b =>
                {
                    b.HasOne("BLL.Entities.Specialist", "Specialist")
                        .WithMany("Schedules")
                        .HasForeignKey("SpecialistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialist");
                });

            modelBuilder.Entity("BLL.Entities.Appointment", b =>
                {
                    b.Navigation("Note");
                });

            modelBuilder.Entity("BLL.Entities.Client", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("BLL.Entities.Specialist", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
